-- migrations/000007_update_menu_schema.up.sql

ALTER TABLE menus
CHANGE COLUMN name title VARCHAR(100) NOT NULL,
CHANGE COLUMN path url VARCHAR(255) NOT NULL,
MODIFY COLUMN parent_id INT UNSIGNED DEFAULT 0,
ADD COLUMN is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN created_at DATETIME(3) NULL,
ADD COLUMN updated_at DATETIME(3) NULL;
